package com.teufel.statusmod.command;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.IntegerArgumentType;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import com.teufel.statusmod.StatusMod;
import com.teufel.statusmod.storage.ModConfig;
import com.teufel.statusmod.storage.PlayerSettings;
import com.teufel.statusmod.util.ColorMapper;
import com.teufel.statusmod.util.CommandUtil;
import com.teufel.statusmod.util.FontMapper;
import com.teufel.statusmod.util.PermissionUtil;
import com.teufel.statusmod.util.StatusTeamUtil;
import com.teufel.statusmod.util.StatusTextUtil;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.TextColor;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StatusCommand {
    private static final Map<String, Preset> PRESETS = new HashMap<>();
    static {
        PRESETS.put("afk", new Preset("AFK", "yellow", "normal"));
        PRESETS.put("busy", new Preset("Busy", "red", "normal"));
        PRESETS.put("stream", new Preset("Stream", "light_purple", "smallcaps"));
        PRESETS.put("shop", new Preset("Shop", "gold", "normal"));
    }

    public static void register(CommandDispatcher<CommandSourceStack> dispatcher) {
        LiteralArgumentBuilder<CommandSourceStack> statusTree = Commands.literal("status")
            .then(Commands.literal("clear").executes(ctx -> { clearStatus(ctx.getSource()); return 1; }))
            .then(Commands.argument("status", StringArgumentType.greedyString()).suggests(CommandSuggestions.STATUS_SUGGESTIONS)
                .then(Commands.argument("color", StringArgumentType.word()).suggests(CommandSuggestions.COLOR_SUGGESTIONS).executes(ctx -> { setStatus(ctx.getSource(), StringArgumentType.getString(ctx, "status"), StringArgumentType.getString(ctx, "color")); return 1; }))
                .executes(ctx -> { setStatus(ctx.getSource(), StringArgumentType.getString(ctx, "status"), null); return 1; }))
            .then(Commands.literal("preset").then(Commands.argument("name", StringArgumentType.word()).suggests(CommandSuggestions.PRESET_SUGGESTIONS).executes(ctx -> { applyPreset(ctx.getSource(), StringArgumentType.getString(ctx, "name")); return 1; })))
            .then(Commands.literal("random").then(Commands.argument("status", StringArgumentType.greedyString()).suggests(CommandSuggestions.STATUS_SUGGESTIONS).executes(ctx -> { setRandomStatus(ctx.getSource(), StringArgumentType.getString(ctx, "status")); return 1; })))
            .then(Commands.literal("timed").then(Commands.argument("minutes", IntegerArgumentType.integer(1)).then(Commands.argument("status", StringArgumentType.greedyString()).suggests(CommandSuggestions.STATUS_SUGGESTIONS).executes(ctx -> { setTimedStatus(ctx.getSource(), IntegerArgumentType.getInteger(ctx, "minutes"), StringArgumentType.getString(ctx, "status")); return 1; }))))
            .then(Commands.literal("history").executes(ctx -> { showHistory(ctx.getSource()); return 1; }))
            .then(Commands.literal("world").then(Commands.literal("clear").executes(ctx -> { clearWorldStatus(ctx.getSource()); return 1; }))
                .then(Commands.argument("status", StringArgumentType.greedyString()).suggests(CommandSuggestions.STATUS_SUGGESTIONS)
                    .then(Commands.argument("color", StringArgumentType.word()).suggests(CommandSuggestions.COLOR_SUGGESTIONS).executes(ctx -> { setWorldStatus(ctx.getSource(), StringArgumentType.getString(ctx, "status"), StringArgumentType.getString(ctx, "color")); return 1; }))
                    .executes(ctx -> { setWorldStatus(ctx.getSource(), StringArgumentType.getString(ctx, "status"), null); return 1; })));
        if (StatusMod.getConfig().enableAdminOverrides) {
            statusTree = statusTree.then(Commands.literal("admin")
                .then(Commands.literal("clear").then(Commands.argument("player", net.minecraft.commands.arguments.EntityArgument.player()).executes(ctx -> { if (!PermissionUtil.hasAdminPermission(ctx.getSource())) { ctx.getSource().sendFailure(Component.literal("Du hast nicht genügend Rechte, um andere Spieler zu verwalten.")); return 0; } ServerPlayer player = net.minecraft.commands.arguments.EntityArgument.getPlayer(ctx, "player"); adminClearStatus(ctx.getSource(), player.getScoreboardName()); return 1; })))
                .then(Commands.literal("set").then(Commands.argument("player", net.minecraft.commands.arguments.EntityArgument.player())
                    .then(Commands.argument("status", StringArgumentType.greedyString()).suggests(CommandSuggestions.STATUS_SUGGESTIONS)
                        .then(Commands.argument("color", StringArgumentType.word()).suggests(CommandSuggestions.COLOR_SUGGESTIONS).executes(ctx -> { if (!PermissionUtil.hasAdminPermission(ctx.getSource())) { ctx.getSource().sendFailure(Component.literal("Du hast nicht genügend Rechte, um andere Spieler zu verwalten.")); return 0; } ServerPlayer player = net.minecraft.commands.arguments.EntityArgument.getPlayer(ctx, "player"); adminSetStatus(ctx.getSource(), player.getScoreboardName(), StringArgumentType.getString(ctx, "status"), StringArgumentType.getString(ctx, "color")); return 1; }))
                        .executes(ctx -> { if (!PermissionUtil.hasAdminPermission(ctx.getSource())) { ctx.getSource().sendFailure(Component.literal("Du hast nicht genügend Rechte, um andere Spieler zu verwalten.")); return 0; } ServerPlayer player = net.minecraft.commands.arguments.EntityArgument.getPlayer(ctx, "player"); adminSetStatus(ctx.getSource(), player.getScoreboardName(), StringArgumentType.getString(ctx, "status"), null); return 1; })))));
        }
        statusTree = statusTree.then(Commands.literal("config").then(Commands.literal("reload").executes(ctx -> { if (!PermissionUtil.hasAdminPermission(ctx.getSource())) { ctx.getSource().sendFailure(Component.literal("Du hast nicht genügend Rechte, um diese Aktion auszuführen.")); return 0; } StatusMod.config = ModConfig.load(); CommandUtil.sendSuccess(ctx.getSource(), Component.literal("StatusMod configuration reloaded."), false); return 1; }))
            .then(Commands.literal("show").executes(ctx -> { if (!PermissionUtil.hasAdminPermission(ctx.getSource())) { ctx.getSource().sendFailure(Component.literal("Du hast nicht genügend Rechte, um diese Aktion auszuführen.")); return 0; } ModConfig c = StatusMod.getConfig(); CommandUtil.sendSuccess(ctx.getSource(), Component.literal("StatusMod configuration:"), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" adminOpLevel = " + c.adminOpLevel), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" statusPermissionNode = " + c.statusPermissionNode), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" adminPermissionNode = " + c.adminPermissionNode), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" enableAdminOverrides = " + c.enableAdminOverrides), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" defaultColor = " + c.defaultColor), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" statusReapplyTicks = " + c.statusReapplyTicks), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" statusCooldownSeconds = " + c.statusCooldownSeconds), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" statusHistorySize = " + c.statusHistorySize), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" enableStaffBadge = " + c.enableStaffBadge), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" staffBadgeText = " + c.staffBadgeText), false); CommandUtil.sendSuccess(ctx.getSource(), Component.literal(" staffBadgeColor = " + c.staffBadgeColor), false); return 1; })));
        dispatcher.register(statusTree);
    }

    private static void setStatus(CommandSourceStack src, String status, String colorKey) {
        try {
            ServerPlayer player = src.getPlayer();
            String uuid = player.getUUID().toString();
            if (StatusMod.getBlockedPlayers().isBlocked(uuid)) { src.sendFailure(Component.literal("Du wurdest vom Status-Mod blockiert.")); return; }
            PlayerSettings settings = StatusMod.getStorage().forPlayer(uuid);
            StatusUpdate update = parseStatusInput(status, colorKey, settings);
            if (!update.ok) { src.sendFailure(Component.literal(update.error)); return; }
            applyStatusUpdate(src, player, settings, update, false, null, false);
            CommandUtil.sendSuccess(src, Component.literal("Status gesetzt: " + update.status + " (" + update.color + ")"), false);
        } catch (Exception e) { try { src.sendFailure(Component.literal("Fehler beim Setzen des Status.")); } catch(Exception ignore){} e.printStackTrace(); }
    }

    private static void clearStatus(CommandSourceStack src) { try { ServerPlayer player = src.getPlayer(); String uuid = player.getUUID().toString(); if (StatusMod.getBlockedPlayers().isBlocked(uuid)) { src.sendFailure(Component.literal("Du wurdest vom Status-Mod blockiert.")); return; } PlayerSettings settings = StatusMod.getStorage().forPlayer(uuid); settings.status=""; settings.color="reset"; settings.statusExpiresAtMs=0L; StatusMod.getStorage().put(uuid, settings); StatusTeamUtil.applyStatus(src.getServer().getScoreboard(), player, settings, "", "reset", PermissionUtil.hasAdminPermission(player)); CommandUtil.sendSuccess(src, Component.literal("Status gelöscht."), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Löschen des Status."));}catch(Exception ignore){} e.printStackTrace();}}

    private static void adminSetStatus(CommandSourceStack src, String targetName, String status, String colorKey) { try { ServerPlayer target = src.getServer().getPlayerList().getPlayerByName(targetName); if (target == null) { src.sendFailure(Component.literal("Spieler '" + targetName + "' ist nicht online.")); return; } PlayerSettings settings = StatusMod.getStorage().forPlayer(target.getUUID().toString()); StatusUpdate update = parseStatusInput(status, colorKey, settings); if (!update.ok) { src.sendFailure(Component.literal(update.error)); return; } applyStatusUpdate(src, target, settings, update, false, null, false); CommandUtil.sendSuccess(src, Component.literal("Status von " + targetName + " gesetzt: " + update.status + " (" + update.color + ")"), false); target.sendSystemMessage(Component.literal("Dein Status wurde von einem Administrator gesetzt."));} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Setzen des Status für '" + targetName + "'."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void adminClearStatus(CommandSourceStack src, String targetName) { try { ServerPlayer target = src.getServer().getPlayerList().getPlayerByName(targetName); if (target == null) { src.sendFailure(Component.literal("Spieler '" + targetName + "' ist nicht online.")); return; } PlayerSettings settings = StatusMod.getStorage().forPlayer(target.getUUID().toString()); settings.status=""; settings.color="reset"; settings.statusExpiresAtMs=0L; StatusMod.getStorage().put(target.getUUID().toString(), settings); StatusTeamUtil.applyStatus(src.getServer().getScoreboard(), target, settings, "", "reset", PermissionUtil.hasAdminPermission(target)); CommandUtil.sendSuccess(src, Component.literal("Status von " + targetName + " gelöscht."), false); target.sendSystemMessage(Component.literal("Dein Status wurde von einem Administrator gelöscht."));} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Löschen des Status für '" + targetName + "'."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void applyPreset(CommandSourceStack src, String name) { try { Preset preset = PRESETS.get((name == null ? "" : name).toLowerCase()); if (preset == null) { src.sendFailure(Component.literal("Unbekanntes Preset: " + name)); return; } ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); if (!checkCooldown(src, settings)) return; StatusUpdate update = new StatusUpdate(preset.status, preset.color, preset.font, true, null); applyStatusUpdate(src, player, settings, update, false, null, false); CommandUtil.sendSuccess(src, Component.literal("Preset gesetzt: " + preset.status + " (" + preset.color + ")"), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Setzen des Presets."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void setRandomStatus(CommandSourceStack src, String statusInput) { try { ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); if (!checkCooldown(src, settings)) return; StatusUpdate update = parseStatusInput(statusInput, null, settings); if (!update.ok) { src.sendFailure(Component.literal(update.error)); return; } update.color = pickStableRandomColor(player.getUUID().toString()); applyStatusUpdate(src, player, settings, update, false, null, false); CommandUtil.sendSuccess(src, Component.literal("Status gesetzt (random): " + update.status + " (" + update.color + ")"), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Setzen des random Status."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void setTimedStatus(CommandSourceStack src, int minutes, String statusInput) { try { ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); if (!checkCooldown(src, settings)) return; StatusUpdate update = parseStatusInput(statusInput, null, settings); if (!update.ok) { src.sendFailure(Component.literal(update.error)); return; } applyStatusUpdate(src, player, settings, update, false, System.currentTimeMillis() + (minutes * 60L * 1000L), false); CommandUtil.sendSuccess(src, Component.literal("Status gesetzt für " + minutes + " Minuten."), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Setzen des Timed-Status."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void setWorldStatus(CommandSourceStack src, String statusInput, String colorKey) { try { ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); if (!checkCooldown(src, settings)) return; StatusUpdate update = parseStatusInput(statusInput, colorKey, settings); if (!update.ok) { src.sendFailure(Component.literal(update.error)); return; } applyStatusUpdate(src, player, settings, update, true, null, false); CommandUtil.sendSuccess(src, Component.literal("World-Status gesetzt."), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Setzen des World-Status."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void clearWorldStatus(CommandSourceStack src) { try { ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); String key = com.teufel.statusmod.util.CompatUtil.getWorldKey(player); if (key != null) { if (settings.statusByWorld != null) settings.statusByWorld.remove(key); if (settings.colorByWorld != null) settings.colorByWorld.remove(key); StatusMod.getStorage().put(player.getUUID().toString(), settings); StatusTeamUtil.applyStatus(src.getServer().getScoreboard(), player, settings, StatusTextUtil.resolveStatusForPlayer(settings, player), StatusTextUtil.resolveColorForPlayer(settings, player), PermissionUtil.hasAdminPermission(player)); } CommandUtil.sendSuccess(src, Component.literal("World-Status gelöscht."), false);} catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Löschen des World-Status."));}catch(Exception ignore){} e.printStackTrace();}}
    private static void showHistory(CommandSourceStack src) { try { ServerPlayer player = src.getPlayer(); if (isBlocked(src, player)) return; PlayerSettings settings = StatusMod.getStorage().forPlayer(player.getUUID().toString()); CommandUtil.sendSuccess(src, Component.literal("Status-Verlauf:"), false); if (settings.statusHistory == null || settings.statusHistory.isEmpty()) { CommandUtil.sendSuccess(src, Component.literal("- (leer)"), false); return; } for (String h : settings.statusHistory) { if (h == null || h.isBlank()) continue; CommandUtil.sendSuccess(src, Component.literal("- " + h), false); } } catch (Exception e){try{src.sendFailure(Component.literal("Fehler beim Anzeigen des Verlaufs."));}catch(Exception ignore){} e.printStackTrace();}}
    private static boolean checkCooldown(CommandSourceStack src, PlayerSettings settings) { try { int cooldown = StatusMod.getConfig() == null ? 0 : StatusMod.getConfig().statusCooldownSeconds; if (cooldown <= 0) return true; if (PermissionUtil.hasAdminPermission(src)) return true; long remaining = (settings.lastStatusChangeAtMs + (cooldown * 1000L)) - System.currentTimeMillis(); if (remaining > 0) { src.sendFailure(Component.literal("Bitte warte " + Math.max(1, remaining / 1000L) + "s bevor du den Status erneut änderst.")); return false; } } catch (Exception ignored) {} return true; }
    private static boolean isBlocked(CommandSourceStack src, ServerPlayer player) { if (player == null) return false; if (StatusMod.getBlockedPlayers().isBlocked(player.getUUID().toString())) { try { src.sendFailure(Component.literal("Du wurdest vom Status-Mod blockiert.")); } catch (Exception ignored) {} return true; } return false; }
    private static void applyStatusUpdate(CommandSourceStack src, ServerPlayer player, PlayerSettings settings, StatusUpdate update, boolean perWorld, Long expiresAtMs, boolean keepFont) { if (player == null || settings == null || update == null) return; if (!keepFont && update.font != null && !update.font.isEmpty()) settings.fontStyle = FontMapper.normalizeStyle(update.font); if (perWorld) { String key = com.teufel.statusmod.util.CompatUtil.getWorldKey(player); if (key != null) { if (settings.statusByWorld != null) settings.statusByWorld.put(key, update.status); if (settings.colorByWorld != null) settings.colorByWorld.put(key, update.color); } } else { settings.status = update.status; settings.color = update.color; } if (expiresAtMs != null) settings.statusExpiresAtMs = expiresAtMs; settings.lastStatusChangeAtMs = System.currentTimeMillis(); addHistory(settings, update.status); StatusMod.getStorage().put(player.getUUID().toString(), settings); var server = src.getServer(); StatusTeamUtil.applyStatus(server.getScoreboard(), player, settings, StatusTextUtil.resolveStatusForPlayer(settings, player), StatusTextUtil.resolveColorForPlayer(settings, player), PermissionUtil.hasAdminPermission(player)); }
    private static void addHistory(PlayerSettings settings, String status) { if (settings == null || status == null || status.isBlank()) return; if (settings.statusHistory == null) settings.statusHistory = new java.util.ArrayList<>(); settings.statusHistory.remove(status); settings.statusHistory.add(status); int max = StatusMod.getConfig() == null ? 5 : StatusMod.getConfig().statusHistorySize; while (settings.statusHistory.size() > max && max > 0) settings.statusHistory.remove(0); if (max <= 0) settings.statusHistory.clear(); }
    private static StatusUpdate parseStatusInput(String statusInput, String colorKey, PlayerSettings settings) { int n = settings.statusWords <= 0 ? 1 : settings.statusWords; String[] tokens = statusInput == null ? new String[0] : statusInput.trim().split("\\s+"); if (tokens.length < n) return StatusUpdate.error("Bitte mindestens " + n + " Wörter für den Status angeben."); StringBuilder sb = new StringBuilder(); for (int i = 0; i < n; i++) { if (i > 0) sb.append(' '); sb.append(tokens[i]); } String status = sb.toString(); String resolvedColor = (colorKey == null || colorKey.isEmpty()) ? ((tokens.length > n) ? tokens[n] : (StatusMod.getConfig() != null && StatusMod.getConfig().defaultColor != null && !StatusMod.getConfig().defaultColor.isEmpty() ? StatusMod.getConfig().defaultColor : "reset")) : colorKey.trim(); if (!ColorMapper.isValidColorInput(resolvedColor)) return StatusUpdate.error("Ungültige Farbe: " + resolvedColor); return new StatusUpdate(status, resolvedColor, settings.fontStyle, true, null); }
    private static String pickStableRandomColor(String uuid) { List<TextColor> palette = ColorMapper.rainbowPalette(); if (palette.isEmpty()) return "reset"; return ColorMapper.toHex(palette.get(Math.abs(uuid.hashCode()) % palette.size())); }
    private static class Preset { final String status; final String color; final String font; Preset(String status, String color, String font) { this.status = status; this.color = color; this.font = font; } }
    private static class StatusUpdate { String status; String color; String font; boolean ok; String error; StatusUpdate(String status, String color, String font, boolean ok, String error) { this.status = status; this.color = color; this.font = font; this.ok = ok; this.error = error; } static StatusUpdate error(String msg) { return new StatusUpdate("", "reset", "normal", false, msg); } }
}
